# This file was generated by generate_homebrew_cask.sh. DO NOT EDIT.
cask "docker-pull-output" do
  name "docker-pull-output"
  desc "Docker Pull Output Parser"
  homepage "https://github.com/na4ma4/docker-pull-output"
  version "1.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "docker-pull-output"

  on_macos do
    on_arm do
      url "https://github.com/na4ma4/docker-pull-output/releases/download/v#{version}/docker-pull-output_darwin_arm64.tar.gz"
      sha256 "d0ac4acd13b2837a4a78cdba6cc76954c17865cebbfa4612325fd3122e836950"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/na4ma4/docker-pull-output/releases/download/v#{version}/docker-pull-output_linux_amd64.tar.gz"
      sha256 "57284d38f55df8f2e619d9a7768e13f3b7bc2703fbd566153d65c36602a72523"
    end
    on_arm do
      url "https://github.com/na4ma4/docker-pull-output/releases/download/v#{version}/docker-pull-output_linux_arm64.tar.gz"
      sha256 "7eaa431badd49e2eb3036e99ef4d24d7f7b91c9f2e38fd09bd130d404ac720d4"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/docker-pull-output"]
    end
  end

  # No zap stanza required
end
