# This file was generated by generate_homebrew_cask.sh. DO NOT EDIT.
cask "docker-pull-output" do
  name "docker-pull-output"
  desc "Docker Pull Output Parser"
  homepage "https://github.com/na4ma4/docker-pull-output"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "docker-pull-output"

  on_macos do
    on_arm do
      url "https://github.com/na4ma4/docker-pull-output/releases/download/v#{version}/docker-pull-output_darwin_arm64.tar.gz"
      sha256 "5c632f68808821916b712e775d22328af9350eb4c34185d2247da57ec4398f33"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/na4ma4/docker-pull-output/releases/download/v#{version}/docker-pull-output_linux_amd64.tar.gz"
      sha256 "885a161de24f8d8ec608fa5d56d90a1b02b238e8ab5070078b14e491ce0609e8"
    end
    on_arm do
      url "https://github.com/na4ma4/docker-pull-output/releases/download/v#{version}/docker-pull-output_linux_arm64.tar.gz"
      sha256 "40a425841d8b5b633738a1a8f6b7fc5e9e415e7702d73fd51acd4ac30427e43b"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/docker-pull-output"]
    end
  end

  # No zap stanza required
end
