# This file was generated by generate_homebrew_cask.sh. DO NOT EDIT.
cask "op-direnv" do
  name "op-direnv"
  desc "1Password Direnv Tool is a command-line utility that integrates 1Password with direnv, allowing you to securely manage environment variables on a per-directory basis using 1Password items."
  homepage "https://github.com/na4ma4/1password-direnv-tool"
  version "v1.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "op-direnv"

  on_macos do
    on_arm do
      url "https://github.com/na4ma4/1password-direnv-tool/releases/download/#{version}/op-direnv_darwin_arm64.tar.gz"
      sha256 "c498c012b1b000dcca701676cb7a8c466e548c7fcc515c5076b54f990baec4cb"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/op-direnv"]
    end
  end

  # No zap stanza required
end
