# This file was generated by generate_homebrew_cask.sh. DO NOT EDIT.
cask "reltime" do
  name "reltime"
  desc "Relative Time is a command-line utility that provides human-readable time differences."
  homepage "https://github.com/na4ma4/relative-time"
  version "v0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "reltime"

  on_macos do
    on_intel do
      sha256 "00adb8a0c84854e0884a4b6d217e916b5648b05e62ec6e6c4d42280e13b015c9"
      url "https://github.com/na4ma4/relative-time/releases/download/#{version}/reltime_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "93a44c905c3c03d9eec7b1e4b607b9ccc198a8209839115a0f4f542f59fb446b"
      url "https://github.com/na4ma4/relative-time/releases/download/#{version}/reltime_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "60090966ac274738bc7b36db1856139f17d8171df94a6ef46c08a4944f5adadc"
      url "https://github.com/na4ma4/relative-time/releases/download/#{version}/reltime_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2bbbc2c1f81f3de9aabef59860d20c1c265fc5864898fbc6cfea1c9fbf2e5fae"
      url "https://github.com/na4ma4/relative-time/releases/download/#{version}/reltime_linux_arm64.tar.gz"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/reltime"]
    end
  end

  # No zap stanza required
end
