# This file was generated by generate-cask.sh. DO NOT EDIT.
cask "ssh-agent-mux" do
  name "ssh-agent-mux"
  desc "SSH Agent Multiplexer"
  homepage "https://github.com/na4ma4/ssh-agent-mux"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssh-agent-mux"

  on_macos do
    on_arm do
      url "https://github.com/na4ma4/ssh-agent-mux/releases/download/#{version}/ssh-agent-mux_darwin_arm64.tar.gz"
      sha256 "c469d5b8c0fdc2647d94e17da6c28942b3421455e8043dd33a43c056ac0006d9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/na4ma4/ssh-agent-mux/releases/download/#{version}/ssh-agent-mux_linux_amd64.tar.gz"
      sha256 "5d90604c1e5dfe46aeda90ef664b72a6af0a9b5108c975fcc127c7c6ed636eb9"
    end
    on_arm do
      url "https://github.com/na4ma4/ssh-agent-mux/releases/download/#{version}/ssh-agent-mux_linux_arm64.tar.gz"
      sha256 "1e7f62fb4ba84dc53ca1536efb1822a6ce658c235dff7c5026110347313a6fcd"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ssh-agent-mux"]
    end
  end

  # No zap stanza required
end
