# This file was generated by generate-cask.sh. DO NOT EDIT.
cask "ssh-agent-mux" do
  name "ssh-agent-mux"
  desc "SSH Agent Multiplexer"
  homepage "https://github.com/na4ma4/ssh-agent-mux"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssh-agent-mux"

  on_macos do
    on_arm do
      url "https://github.com/na4ma4/ssh-agent-mux/releases/download/v#{version}/ssh-agent-mux_darwin_arm64.tar.gz"
      sha256 "400218ccff34056e067aaaf88f2a71ba75fa5c7d41cc5c077e1435e211ca4aa7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/na4ma4/ssh-agent-mux/releases/download/v#{version}/ssh-agent-mux_linux_amd64.tar.gz"
      sha256 "c81851a58f38620791838f5e45316997378a346c109db6c924d4a91a5abf6085"
    end
    on_arm do
      url "https://github.com/na4ma4/ssh-agent-mux/releases/download/v#{version}/ssh-agent-mux_linux_arm64.tar.gz"
      sha256 "ccddb42985d8167828e48c4392683d69f4c31c61dcaf254c6a2094d92e5e2d6d"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ssh-agent-mux"]
    end
  end

  # No zap stanza required
end
