# This file was generated by generate-cask.sh. DO NOT EDIT.
cask "ssh-agent-mux" do
  name "ssh-agent-mux"
  desc "SSH Agent Multiplexer"
  homepage "https://github.com/na4ma4/ssh-agent-mux"
  version "0.2.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssh-agent-mux"

  on_macos do
    on_arm do
      url "https://github.com/na4ma4/ssh-agent-mux/releases/download/v#{version}/ssh-agent-mux_darwin_arm64.tar.gz"
      sha256 "f5615b168bb2a6409229395cd254fe52eb9ddeee1eb5bba4496f596e80e86d2a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/na4ma4/ssh-agent-mux/releases/download/v#{version}/ssh-agent-mux_linux_amd64.tar.gz"
      sha256 "817307292d70f146c1aa1d1384824d9811134759a5d69976ef6178eb1b7cdf61"
    end
    on_arm do
      url "https://github.com/na4ma4/ssh-agent-mux/releases/download/v#{version}/ssh-agent-mux_linux_arm64.tar.gz"
      sha256 "91520ac82540f9065ec0d042b721905f0a5485d7e31d2cc35ebfcab21e90c026"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ssh-agent-mux"]
    end
  end

  # No zap stanza required
end
