# This file was generated by generate_homebrew_cask.sh. DO NOT EDIT.
cask "traefik-acme" do
  name "traefik-acme"
  desc "Traefik ACME Plugin"
  homepage "https://github.com/na4ma4/traefik-acme"
  version "0.5.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "traefik-acme"

  on_macos do
    on_arm do
      url "https://github.com/na4ma4/traefik-acme/releases/download/v#{version}/traefik-acme_darwin_arm64.tar.gz"
      sha256 "7d5673f5c377d7f48b20bf4c8abac0fb0bf09fb9cf34bcf5ac15a37d2e656632"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/na4ma4/traefik-acme/releases/download/v#{version}/traefik-acme_linux_amd64.tar.gz"
      sha256 "f88e6ef1d38c7abd271951a2d61784ae8db91550b0777ea20cc1afb492cb5e72"
    end
    on_arm do
      url "https://github.com/na4ma4/traefik-acme/releases/download/v#{version}/traefik-acme_linux_arm64.tar.gz"
      sha256 "02cacc2365b9ff3473aa9a85cf8eece509cf5fab00dcadaf02704de1e29fa628"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/traefik-acme"]
    end
  end

  # No zap stanza required
end
