# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CrlUpdater < Formula
  desc "CRL local file update"
  homepage "https://github.com/na4ma4/crl-updater"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/na4ma4/crl-updater/releases/download/v0.1.0/crl-updater_0.1.0_darwin_amd64.tar.gz"
      sha256 "efc77540f92d549a4fb1a92e31caae2f6cf21831c496bcadabcbcb2a92a52b26"

      def install
        bin.install "crl-updater"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/na4ma4/crl-updater/releases/download/v0.1.0/crl-updater_0.1.0_darwin_arm64.tar.gz"
      sha256 "ed5403b451c5ef8969e872d5485f6dbae80bc27e4833f1e4259256451816afcc"

      def install
        bin.install "crl-updater"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/na4ma4/crl-updater/releases/download/v0.1.0/crl-updater_0.1.0_linux_arm64.tar.gz"
      sha256 "fcc6cde44d6342f3221d04899aee198aa77463115fb2b6b0e92a4d87c3bf9603"

      def install
        bin.install "crl-updater"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/na4ma4/crl-updater/releases/download/v0.1.0/crl-updater_0.1.0_linux_amd64.tar.gz"
      sha256 "07d77acf24b8a5564f2877304547a58a01bb2d19db92ccc5d5805b5491500195"

      def install
        bin.install "crl-updater"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/na4ma4/crl-updater/releases/download/v0.1.0/crl-updater_0.1.0_linux_armv6.tar.gz"
      sha256 "14820b7bc7dcf3e8ce76275e25b827259e142e1ed277272719c94591a329815e"

      def install
        bin.install "crl-updater"
      end
    end
  end

  test do
    system "#{bin}/crl-updater --version"
  end
end
