# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CrlUpdater < Formula
  desc "CRL local file update"
  homepage "https://github.com/na4ma4/crl-updater"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/na4ma4/crl-updater/releases/download/v0.2.0/crl-updater_0.2.0_darwin_amd64.tar.gz"
      sha256 "ab523618df07e431bd8dd2b36f24d58f2b81cd5dadff77d88686d8e79805416b"

      def install
        bin.install "crl-updater"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/na4ma4/crl-updater/releases/download/v0.2.0/crl-updater_0.2.0_darwin_arm64.tar.gz"
      sha256 "3fea2fa059b9be07b61b5e33011581062a8dd31b15ee41da5ff64f6796fe75b7"

      def install
        bin.install "crl-updater"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/na4ma4/crl-updater/releases/download/v0.2.0/crl-updater_0.2.0_linux_armv6.tar.gz"
      sha256 "1586ef63c212cc389a5b79f2175db3c487ed4e1ae2a8c19b75b4f505c0a42e77"

      def install
        bin.install "crl-updater"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/na4ma4/crl-updater/releases/download/v0.2.0/crl-updater_0.2.0_linux_amd64.tar.gz"
      sha256 "8d2d16bf08fff8d1814d65e19573b91ff4f3df4e9ccb989dd3066dbb630f39d7"

      def install
        bin.install "crl-updater"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/na4ma4/crl-updater/releases/download/v0.2.0/crl-updater_0.2.0_linux_arm64.tar.gz"
      sha256 "66a0981332b10cd8ab198a73cdb293cfba68b6e72bd2a482122ad5995e04414a"

      def install
        bin.install "crl-updater"
      end
    end
  end

  test do
    system "#{bin}/crl-updater --version"
  end
end
