# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CrtshLs < Formula
  desc "crt.sh list command line tool."
  homepage "https://github.com/na4ma4/crtsh-ls"
  version "0.9.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/na4ma4/crtsh-ls/releases/download/v0.9.1/crtsh-ls_0.9.1_darwin_amd64.tar.gz"
      sha256 "64e10d84c33a59243cc7994a99e38337b0101cd8e99e9e96dee55a29a574adb0"

      def install
        bin.install "crtsh-ls"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/na4ma4/crtsh-ls/releases/download/v0.9.1/crtsh-ls_0.9.1_darwin_arm64.tar.gz"
      sha256 "9add568f3988bac41dfafcb29b6e174982a3ebf69c2e8623209923603b05875c"

      def install
        bin.install "crtsh-ls"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/na4ma4/crtsh-ls/releases/download/v0.9.1/crtsh-ls_0.9.1_linux_amd64.tar.gz"
      sha256 "e4e8afb23ab62933a3792b2e154bc339212154ef326acbc157f44fb39690c9d8"

      def install
        bin.install "crtsh-ls"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/na4ma4/crtsh-ls/releases/download/v0.9.1/crtsh-ls_0.9.1_linux_armv6.tar.gz"
      sha256 "e170753bca1d3e7533ba9667acb97e1daa168e4246bc8576ec359934f4772333"

      def install
        bin.install "crtsh-ls"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/na4ma4/crtsh-ls/releases/download/v0.9.1/crtsh-ls_0.9.1_linux_arm64.tar.gz"
      sha256 "7139b8b64357ee7926cf48b3464ee419c1ff1dca09b92956d792657e6b020afd"

      def install
        bin.install "crtsh-ls"
      end
    end
  end

  test do
    system "#{bin}/crtsh-ls --version"
  end
end
