# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CrtshLs < Formula
  desc "crt.sh list command line tool."
  homepage "https://github.com/na4ma4/crtsh-ls"
  version "0.9.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/na4ma4/crtsh-ls/releases/download/v0.9.0/crtsh-ls_0.9.0_darwin_arm64.tar.gz"
      sha256 "69ef458b31acec0e6288d39c2ef45ae705fdd620a9a551b0a07300d4694cc7a6"

      def install
        bin.install "crtsh-ls"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/na4ma4/crtsh-ls/releases/download/v0.9.0/crtsh-ls_0.9.0_darwin_amd64.tar.gz"
      sha256 "423c1c3fb2e30935f00aacb87812c7675b5f6a5d043c1ff0a51b85b9e136faf1"

      def install
        bin.install "crtsh-ls"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/na4ma4/crtsh-ls/releases/download/v0.9.0/crtsh-ls_0.9.0_linux_arm64.tar.gz"
      sha256 "18fc4e8b68e6720ccdf62c3efc3138bcb7d197aece7614945bc955f2a6704e75"

      def install
        bin.install "crtsh-ls"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/na4ma4/crtsh-ls/releases/download/v0.9.0/crtsh-ls_0.9.0_linux_armv6.tar.gz"
      sha256 "8a5bb52e99c66f99e633411cecf0eedb9d078260d4ad4d4a040642336ce9ba23"

      def install
        bin.install "crtsh-ls"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/na4ma4/crtsh-ls/releases/download/v0.9.0/crtsh-ls_0.9.0_linux_amd64.tar.gz"
      sha256 "c87c728e22b7cd739fb45b24c169c4c6b80716d7ba6b4b5d47b7aaa7104453d9"

      def install
        bin.install "crtsh-ls"
      end
    end
  end

  test do
    system "#{bin}/crtsh-ls --version"
  end
end
