# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghtool < Formula
  desc "GitHub API Tool"
  homepage "https://github.com/na4ma4/ghtool"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/na4ma4/ghtool/releases/download/v0.4.0/ghtool_0.4.0_darwin_amd64.tar.gz"
      sha256 "2875bf05c89d530f3cc7d7538440462feb5eb83c0129badc77f6ca1d304aba43"

      def install
        bin.install "ghtool"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/na4ma4/ghtool/releases/download/v0.4.0/ghtool_0.4.0_darwin_arm64.tar.gz"
      sha256 "fad9c9527ab811edc88c880cbcf824b2c37f8a1690d8cf9a6e847de378d7f950"

      def install
        bin.install "ghtool"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/na4ma4/ghtool/releases/download/v0.4.0/ghtool_0.4.0_linux_amd64.tar.gz"
        sha256 "bedce98cde0d3c4a9b138d87fb3fcc3674a1cffb32a8bf7577db6ebb0a2a4e0b"

        def install
          bin.install "ghtool"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/na4ma4/ghtool/releases/download/v0.4.0/ghtool_0.4.0_linux_armv6.tar.gz"
        sha256 "d17dda7444fbb6fb3814742e7bd27658bdcc6b808bc750a90fe398d7bb7bbfb9"

        def install
          bin.install "ghtool"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/na4ma4/ghtool/releases/download/v0.4.0/ghtool_0.4.0_linux_arm64.tar.gz"
        sha256 "cc0d19adfbee10b20d1a95d54874611b6967ac4fe6927fe9e096541d0ae675d6"

        def install
          bin.install "ghtool"
        end
      end
    end
  end

  test do
    system "#{bin}/ghtool --version"
  end
end
