# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghtool < Formula
  desc "GitHub API Tool"
  homepage "https://github.com/na4ma4/ghtool"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/na4ma4/ghtool/releases/download/v0.1.0/ghtool_0.1.0_darwin_arm64.tar.gz"
      sha256 "a38e8fb454a10d9d6230214a840653e3c85579b37dcae9d2aee80e9fa34adecd"

      def install
        bin.install "ghtool"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/na4ma4/ghtool/releases/download/v0.1.0/ghtool_0.1.0_darwin_amd64.tar.gz"
      sha256 "643048338af017ee41bbda19fbbc0919218249911c07ab853f0b82a222b5eea5"

      def install
        bin.install "ghtool"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/na4ma4/ghtool/releases/download/v0.1.0/ghtool_0.1.0_linux_arm64.tar.gz"
      sha256 "4b2f8ace7dc4cdc4e754b02dfde51440a5529e3067d754b7d077bca5ed17b97b"

      def install
        bin.install "ghtool"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/na4ma4/ghtool/releases/download/v0.1.0/ghtool_0.1.0_linux_amd64.tar.gz"
      sha256 "8763281f8df32b572f4a2fc2c628cb2280d991bfffd9bc5ea841eceb1372c792"

      def install
        bin.install "ghtool"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/na4ma4/ghtool/releases/download/v0.1.0/ghtool_0.1.0_linux_armv6.tar.gz"
      sha256 "8f14b06d4f9c5c03a08b88bdf85676fc039b1a65773a7c78d9de3b32f6616817"

      def install
        bin.install "ghtool"
      end
    end
  end

  test do
    system "#{bin}/ghtool --version"
  end
end
