# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reltime < Formula
  desc "Relative time check tool"
  homepage "https://github.com/na4ma4/relative-time"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/na4ma4/relative-time/releases/download/v0.1.0/relative-time_0.1.0_darwin_arm64.tar.gz"
      sha256 "f92288cad43562ba6a316978ef4bcb5a397d43a50c9428b817c4a7fc732bd61f"

      def install
        bin.install "reltime"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/na4ma4/relative-time/releases/download/v0.1.0/relative-time_0.1.0_darwin_amd64.tar.gz"
      sha256 "f38a2687dd26eb87e44d6df7f3c515d359eff0a292c14d6c96938adc906d49e9"

      def install
        bin.install "reltime"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/na4ma4/relative-time/releases/download/v0.1.0/relative-time_0.1.0_linux_armv6.tar.gz"
      sha256 "735e9c102ed4b0bfbf42459253e720460d679c41e83ddda4b2baf4b5be1d8833"

      def install
        bin.install "reltime"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/na4ma4/relative-time/releases/download/v0.1.0/relative-time_0.1.0_linux_arm64.tar.gz"
      sha256 "e809592b4fd6cf45cea8e1917fd05724c912dd46ff4d62c24f5e45c2b5c92994"

      def install
        bin.install "reltime"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/na4ma4/relative-time/releases/download/v0.1.0/relative-time_0.1.0_linux_amd64.tar.gz"
      sha256 "f4613197adc2c18ac65eeae4b12dd665f0809b6b0d78992924e4397380bc7c0b"

      def install
        bin.install "reltime"
      end
    end
  end

  test do
    system "#{bin}/reltime --version"
  end
end
