# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reltime < Formula
  desc "Relative time check tool"
  homepage "https://github.com/na4ma4/relative-time"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/na4ma4/relative-time/releases/download/v0.2.0/relative-time_0.2.0_darwin_arm64.tar.gz"
      sha256 "16674723d28bbd1cb68aa7d6ef6f6984921be8ce4dfdd8602d345f124ca95ad6"

      def install
        bin.install "reltime"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/na4ma4/relative-time/releases/download/v0.2.0/relative-time_0.2.0_darwin_amd64.tar.gz"
      sha256 "f238d6fdbb34323a041680493179ea3965e48a94178526402510a035027d22cc"

      def install
        bin.install "reltime"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/na4ma4/relative-time/releases/download/v0.2.0/relative-time_0.2.0_linux_amd64.tar.gz"
      sha256 "09bacff2512a58096f5fbd271b5ef645663f584a7712b4034ab66e1d9b2eaba0"

      def install
        bin.install "reltime"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/na4ma4/relative-time/releases/download/v0.2.0/relative-time_0.2.0_linux_armv6.tar.gz"
      sha256 "479f65605db7883029be21ecaa581d96b6b2c3880406d0048f7225ba7016f4b9"

      def install
        bin.install "reltime"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/na4ma4/relative-time/releases/download/v0.2.0/relative-time_0.2.0_linux_arm64.tar.gz"
      sha256 "75780e7822574e696088e2a6fe07c90846a2cf88b1545919df1bcc775e081163"

      def install
        bin.install "reltime"
      end
    end
  end

  test do
    system "#{bin}/reltime --version"
  end
end
