# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssh-agent-mux" do
  name "ssh-agent-mux"
  desc "SSH Agent Multiplexer"
  homepage "https://github.com/na4ma4/ssh-agent-mux"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssh-agent-mux"

  on_macos do
    on_arm do
      url "https://github.com/na4ma4/ssh-agent-mux/releases/download/#{version}/ssh-agent-mux_#{version}_darwin_arm64.tar.gz"
      sha256 "98e81130c6c64742ddfaf30d1a9f0e32dd556c5816dc0e4a7d2c6c31ae56f78a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/na4ma4/ssh-agent-mux/releases/download/#{version}/ssh-agent-mux_#{version}_linux_amd64.tar.gz"
      sha256 "c7375208b86c742c7f951a3ee745c96f4599c682b755a27ebe4859dd8ee6efe0"
    end
    on_arm do
      url "https://github.com/na4ma4/ssh-agent-mux/releases/download/#{version}/ssh-agent-mux_#{version}_linux_arm64.tar.gz"
      sha256 "a22633cdfb08fc6f43a8613092204e696a2e44633a51c575ff50a85bf0710381"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ssh-agent-mux"]
    end
  end

  # No zap stanza required
end
